version: '3.7'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodbcontainer
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - APP_MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_ROOT_USER=${MONGO_ROOT_USERNAME}
      - MONGO_ROOT_PASS=${MONGO_ROOT_PASSWORD}
      - APP_MONGO_USER=${APP_MONGO_USER}
      - APP_MONGO_PASS=${APP_MONGO_PASS}
      - APP_MONGO_DB=${APP_MONGO_DB}
    ports:
      - "27017:27017"
    volumes:
      - ./build/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
  webapi:
    build: .
    command: npm run start:prod
    container_name: webapicontainer
    restart: always
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
      - ./src:/usr/app/
    ports:
      - "3000:3000"
    links:
      - mongodb
    depends_on:
      - mongodb
